### PR TITLE
include contribute styling rules

### PR DESCRIPTION
**Pull request by mrmorante**
Introduced contributing changes as discussed, w/ some minor changes to it

### CODE REVIEW

**Comment by strattadb** [comment]
I'm not sure about `you'd rather just link it`. Isn't it an affirmation about what the reader prefers? Or am I missing something?

**Comment by ssassi** [comment]
Maybe a better spelling could be `you should rather link it`.

**Comment by mrmorante** [comment]
How about `...just link it`?

**Comment by mrmorante** [comment]
Done. Wording updated.

**Pull request merged**
